# Generated by Django 2.0.3 on 2018-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMO', '0002_auto_20180330_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
